name: deploy

on:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.TIPPY_JP_GITHUB_TOKEN }}
        run: ./build.sh

      - name: Setup
        uses: actions/configure-pages@v3

      - name: Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v2
