name: deploy

on:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh
        env:
          GH_TOKEN: ${{ secrets.TIPPY_JP_GITHUB_TOKEN }}

      - name: Setup
        uses: actions/configure-pages@v5

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy
        uses: actions/deploy-pages@v4
